## Cleaning our scrapped Oscar's CSV ##

In [1]:
import os

ruta_csv = os.path.abspath('nombre_del_archivo.csv')
print(ruta_csv)

/Users/davidusuariocasa/Desktop/Projects/ETL_project/nombre_del_archivo.csv

In [84]:
import pandas as pd


scrapped = pd.read_csv('/Users/davidusuariocasa/Desktop/Projects/ETL_project/Data/scrapped.csv'
)

In [85]:
scrapped = scrapped.dropna() # First, we remove all columns that contain at least one null value

scrapped = scrapped.reset_index() # Now we reset the indexes

scrapped = scrapped.drop('index', axis=1) # And finally we remove the column 'index'

## Converting our 'duration' column to minutes ##

In [86]:
import re # We import the regex library

# We want to convert the values in our 'duration' column to minutes, so we create a function to do so

def convert_duration_to_minutes(duration_str): 
    hours = re.findall(r'\d+h', duration_str) # we use regex to get all values followed by an 'h' (hours) and store them
    minutes = re.findall(r'\d+min', duration_str) # the same, but with mins

    hours = int(hours[0].rstrip('h')) if hours else 0 # If regex finds hours, we take out the 'h' and store the number
    minutes = int(minutes[0].rstrip('min')) if minutes else 0 # If regex finds mins, we take 'mins' and store the number

    total_minutes = hours * 60 + minutes # since we want everything in mins, we multiply the hours by 60 and add the remaining minutes

    return total_minutes # our function returns the total mins

In [87]:
scrapped['duration'] = scrapped['duration'].apply(convert_duration_to_minutes) # we apply the function to our 'duration' column

## Changing our 'score' column ##

In [97]:
# We create a function that takes the values from our 'score' column, and just takes the score

def clean_rating(value):
    parts = value.split('\n/')
    if len(parts) == 2:
        return parts[0]
    else:
        return value

In [98]:
scrapped['score'] = scrapped['score'].apply(clean_rating) # we apply the function to our 'score' column

In [99]:
scrapped

,year_film,year_ceremony,ceremony,category,name,film,duration,score
0,1927,1928,1,ACTOR,Emil Jannings,The Last Command,88,"8,0"
1,1927,1928,1,ART DIRECTION,William Cameron Menzies,The Dove;,90,"6,5"
2,1927,1928,1,CINEMATOGRAPHY,Charles Rosher,Sunrise,94,"8,1"
3,1927,1928,1,CINEMATOGRAPHY,Karl Struss,Sunrise,94,"8,1"
4,1927,1928,1,DIRECTING (Comedy Picture),Lewis Milestone,Two Arabian Knights,92,"6,7"
...,...,...,...,...,...,...,...,...
1931,2022,2023,95,SOUND,"Mark Weingarten, James H. Mather, Al Nelson, C...",Top Gun: Maverick,130,"8,3"
1932,2022,2023,95,VISUAL EFFECTS,"Joe Letteri, Richard Baneham, Eric Saindon and...",Avatar: The Way of Water,192,"7,6"
1933,2022,2023,95,WRITING (Adapted Screenplay),Screenplay by Sarah Polley,Women Talking,104,"6,9"
1934,2022,2023,95,WRITING (Original Screenplay),Written by Daniel Kwan & Daniel Scheinert,Everything Everywhere All at Once,139,"7,8"
1935,2022,2023,95,AWARD OF COMMENDATION,To Ryan Laney for his innovative adaptation an...,Welcome to Chechnya,107,"7,9"