In [208]:
import os

# Get the current working directory
current_directory = os.getcwd()

# Print the current working directory
print(current_directory)

/Users/davidusuariocasa/Desktop/Projects/ETL_project

In [235]:
import pandas as pd

In [236]:
movies = pd.read_csv('/Users/davidusuariocasa/Desktop/oscars.csv')

movies

,year_film,year_ceremony,ceremony,category,name,film,winner
0,1927,1928,1,ACTOR,Richard Barthelmess,The Noose,False
1,1927,1928,1,ACTOR,Emil Jannings,The Last Command,True
2,1927,1928,1,ACTRESS,Louise Dresser,A Ship Comes In,False
3,1927,1928,1,ACTRESS,Janet Gaynor,7th Heaven,True
4,1927,1928,1,ACTRESS,Gloria Swanson,Sadie Thompson,False
...,...,...,...,...,...,...,...
10760,2022,2023,95,HONORARY AWARD,"To Euzhan Palcy, a masterful filmmaker who bro...",NaN,True
10761,2022,2023,95,HONORARY AWARD,"To Diane Warren, for her genius, generosity an...",NaN,True
10762,2022,2023,95,HONORARY AWARD,"To Peter Weir, a fearless and consummate filmm...",NaN,True
10763,2022,2023,95,GORDON E. SAWYER AWARD,Iain Neil,NaN,True
10764,2022,2023,95,AWARD OF COMMENDATION,To Ryan Laney for his innovative adaptation an...,Welcome to Chechnya,True

In [285]:
filtered_df = movies[movies['winner'] == True] # I filter by 'True' only to show the winners and discard the nominated who didn't win (those with value 'False')

filtered_df

,year_film,year_ceremony,ceremony,category,name,film,winner
1,1927,1928,1,ACTOR,Emil Jannings,The Last Command,True
3,1927,1928,1,ACTRESS,Janet Gaynor,7th Heaven,True
6,1927,1928,1,ART DIRECTION,William Cameron Menzies,The Dove;,True
9,1927,1928,1,CINEMATOGRAPHY,Charles Rosher,Sunrise,True
10,1927,1928,1,CINEMATOGRAPHY,Karl Struss,Sunrise,True
...,...,...,...,...,...,...,...
10760,2022,2023,95,HONORARY AWARD,"To Euzhan Palcy, a masterful filmmaker who bro...",NaN,True
10761,2022,2023,95,HONORARY AWARD,"To Diane Warren, for her genius, generosity an...",NaN,True
10762,2022,2023,95,HONORARY AWARD,"To Peter Weir, a fearless and consummate filmm...",NaN,True
10763,2022,2023,95,GORDON E. SAWYER AWARD,Iain Neil,NaN,True
10764,2022,2023,95,AWARD OF COMMENDATION,To Ryan Laney for his innovative adaptation an...,Welcome to Chechnya,True

In [286]:
null_rows = filtered_df[movies.isnull().any(axis=1)] # I do this to see which rows contain null values

no_nulls = filtered_df.dropna()

no_nulls # now I have all the winners, without null values

,year_film,year_ceremony,ceremony,category,name,film,winner
1,1927,1928,1,ACTOR,Emil Jannings,The Last Command,True
3,1927,1928,1,ACTRESS,Janet Gaynor,7th Heaven,True
6,1927,1928,1,ART DIRECTION,William Cameron Menzies,The Dove;,True
9,1927,1928,1,CINEMATOGRAPHY,Charles Rosher,Sunrise,True
10,1927,1928,1,CINEMATOGRAPHY,Karl Struss,Sunrise,True
...,...,...,...,...,...,...,...
10743,2022,2023,95,SOUND,"Mark Weingarten, James H. Mather, Al Nelson, C...",Top Gun: Maverick,True
10745,2022,2023,95,VISUAL EFFECTS,"Joe Letteri, Richard Baneham, Eric Saindon and...",Avatar: The Way of Water,True
10753,2022,2023,95,WRITING (Adapted Screenplay),Screenplay by Sarah Polley,Women Talking,True
10755,2022,2023,95,WRITING (Original Screenplay),Written by Daniel Kwan & Daniel Scheinert,Everything Everywhere All at Once,True
10764,2022,2023,95,AWARD OF COMMENDATION,To Ryan Laney for his innovative adaptation an...,Welcome to Chechnya,True

In [287]:
columns_to_drop = ['winner', 'name']

no_nulls.drop(columns=columns_to_drop, inplace=True) # Now I remove the column 'winner', since now I only have winners in my dataframe

In [288]:
no_nulls

,year_film,year_ceremony,ceremony,category,film
1,1927,1928,1,ACTOR,The Last Command
3,1927,1928,1,ACTRESS,7th Heaven
6,1927,1928,1,ART DIRECTION,The Dove;
9,1927,1928,1,CINEMATOGRAPHY,Sunrise
10,1927,1928,1,CINEMATOGRAPHY,Sunrise
...,...,...,...,...,...
10743,2022,2023,95,SOUND,Top Gun: Maverick
10745,2022,2023,95,VISUAL EFFECTS,Avatar: The Way of Water
10753,2022,2023,95,WRITING (Adapted Screenplay),Women Talking
10755,2022,2023,95,WRITING (Original Screenplay),Everything Everywhere All at Once
10764,2022,2023,95,AWARD OF COMMENDATION,Welcome to Chechnya

In [289]:
selected_categories = ['OUTSTANDING PICTURE', 'UNIQUE AND ARTISTIC PICTURE', 'OUTSTANDING PRODUCTION', 'SHORT SUBJECT (Cartoon)', 'SHORT SUBJECT (Comedy)', 'SHORT SUBJECT (Novelty)', 'ASSISTANT DIRECTOR', 'MUSIC (Scoring)', 'MUSIC (Song)', 'DANCE DIRECTION', 'SHORT SUBJECT (Color)', 'SHORT SUBJECT (One-reel)', 'SHORT SUBJECT (Two-reel)', 'SPECIAL EFFECTS', 'DOCUMENTARY (Short Subject)', 'DOCUMENTARY (Feature)', 'FOREIGN LANGUAGE FILM', 'BEST PICTURE', 'SHORT FILM (Animated)', 'SHORT FILM (Live Action)', 'SHORT FILM (Dramatic Live Action)', 'ANIMATED FEATURE FILM', 'INTERNATIONAL FEATURE FILM', 'DOCUMENTARY FEATURE FILM', 'DOCUMENTARY SHORT FILM']

finaldf = no_nulls[no_nulls['category'].isin(selected_categories)] # I select only those winning categories that I consider represent best the film itself

finaldf.reset_index(inplace = True) # I reset the indexes

In [290]:
finaldf = finaldf.drop(columns='index') # We remove the column 'index'

In [291]:
finaldf

,year_film,year_ceremony,ceremony,category,film
0,1927,1928,1,OUTSTANDING PICTURE,Wings
1,1927,1928,1,UNIQUE AND ARTISTIC PICTURE,Sunrise
2,1928,1929,2,OUTSTANDING PICTURE,The Broadway Melody
3,1929,1930,3,OUTSTANDING PRODUCTION,All Quiet on the Western Front
4,1930,1931,4,OUTSTANDING PRODUCTION,Cimarron
...,...,...,...,...,...
586,2022,2023,95,DOCUMENTARY SHORT FILM,The Elephant Whisperers
587,2022,2023,95,INTERNATIONAL FEATURE FILM,All Quiet on the Western Front
588,2022,2023,95,BEST PICTURE,Everything Everywhere All at Once
589,2022,2023,95,SHORT FILM (Animated),"The Boy, the Mole, the Fox and the Horse"
590,2022,2023,95,SHORT FILM (Live Action),An Irish Goodbye

In [292]:
# Now to do our web scraping, we need to import all these libraries

import numpy as np 
from selenium import webdriver # webdriver permite manejar un navegador 
from webdriver_manager.chrome import ChromeDriverManager # permite instalar y mantener actualizado el driver de chrome
from selenium.webdriver.common.keys import Keys # permite simular teclas del teclado 
from selenium.webdriver.chrome.options import Options # permite configurar el driver de chrome como modo incognito o maximizar la ventana
import time # esperas entre ejecuciones de codigo
import random


import warnings # permite ignorar los warnings de python 
warnings.filterwarnings('ignore')

In [293]:
opciones= Options()
opciones.add_experimental_option('excludeSwitches', ['enable-automation'])
#para ocultarme como robot
opciones.add_experimental_option('useAutomationExtension', False)
opciones.add_argument('--start-maximized') #empezar maximizado
opciones.add_argument('user.data-dir=selenium') #guarda las cookies
opciones.add_argument('--incognito')#incognito window

In [294]:
driver = webdriver.Firefox()

tiempo_espera = random.uniform(0.5, 1)

for index, (value, year) in enumerate(zip(finaldf['film'], finaldf['year_film'])):
    driver = webdriver.Firefox()
    driver.get("https://www.google.com/webhp?hl=es&sa=X&ved=0ahUKEwib6NqMzP7_AhUbVqQEHU22BKcQPAgJ")
    driver.implicitly_wait(2)

    try:
        driver.find_element("css selector","#L2AGLb > div:nth-child(1)").click() # We click to accept the cookies
    except:
        pass

    driver.find_element("css selector","#APjFqb").send_keys(f'"{value} {str(year)}"' + ' ' + 'site:https://www.boxofficemojo.com/', Keys.ENTER) # We select the search box with each film and year

    try:
        driver.find_element("css selector",".LC20lb").click() # If we get results, we click on the link

        try:
            box_office = driver.find_element('css selector','.mojo-performance-summary-table > div:nth-child(4) > span:nth-child(3) > span:nth-child(1)').text # If the page shows the box office, we store the value in a variable called 'box_office'
            finaldf.loc[index, 'box_office'] = box_office

        except:
            finaldf.loc[index, 'box_office'] = np.nan # If not, we store the value as null
    except:
        finaldf.loc[index, 'box_office'] = np.nan

    driver.quit()
    time.sleep(2)  # Esperar 2 segundos antes de abrir el navegador nuevamente

driver.quit()

NoSuchElementException: Message: Unable to locate element: #APjFqb; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:183:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:395:5
element.find/</<@chrome://remote/content/marionette/element.sys.mjs:134:16

In [314]:
df_sin_url = finaldf[finaldf['box_office'].isnull()]

,year_film,year_ceremony,ceremony,category,film,box_office
2,1928,1929,2,OUTSTANDING PICTURE,The Broadway Melody,NaN
3,1929,1930,3,OUTSTANDING PRODUCTION,All Quiet on the Western Front,NaN
4,1930,1931,4,OUTSTANDING PRODUCTION,Cimarron,NaN
5,1931,1932,5,OUTSTANDING PRODUCTION,Grand Hotel,NaN
6,1931,1932,5,SHORT SUBJECT (Cartoon),Flowers and Trees,NaN
...,...,...,...,...,...,...
586,2022,2023,95,DOCUMENTARY SHORT FILM,The Elephant Whisperers,NaN
587,2022,2023,95,INTERNATIONAL FEATURE FILM,All Quiet on the Western Front,NaN
588,2022,2023,95,BEST PICTURE,Everything Everywhere All at Once,NaN
589,2022,2023,95,SHORT FILM (Animated),"The Boy, the Mole, the Fox and the Horse",NaN
590,2022,2023,95,SHORT FILM (Live Action),An Irish Goodbye,NaN

In [316]:
finaldf_verdadero = finaldf[~finaldf['box_office'].isnull()]

,year_film,year_ceremony,ceremony,category,film,box_office
0,1927,1928,1,OUTSTANDING PICTURE,Wings,$746
1,1927,1928,1,UNIQUE AND ARTISTIC PICTURE,Sunrise,"$121,107"
15,1934,1935,7,MUSIC (Song),The Gay Divorcee,"$6,253"
16,1934,1935,7,OUTSTANDING PRODUCTION,It Happened One Night,"$11,477"
53,1939,1940,12,MUSIC (Song),The Wizard of Oz,"$25,637,669"
54,1939,1940,12,OUTSTANDING PRODUCTION,Gone with the Wind,"$402,382,193"
60,1940,1941,13,MUSIC (Song),Pinocchio,"$121,892,045"
61,1940,1941,13,OUTSTANDING PRODUCTION,Rebecca,"$72,275"
86,1944,1945,17,MUSIC (Song),Going My Way,"$2,221"

In [317]:
def scrapeo(df_):
    driver = webdriver.Firefox()

    tiempo_espera = random.uniform(0.5, 1)

    for index, (value, year) in enumerate(zip(df_['film'], df_['year_film'])):
        driver = webdriver.Firefox()
        driver.get("https://www.google.com/webhp?hl=es&sa=X&ved=0ahUKEwib6NqMzP7_AhUbVqQEHU22BKcQPAgJ")
        driver.implicitly_wait(2)

        try:
            driver.find_element("css selector","#L2AGLb > div:nth-child(1)").click() # We click to accept the cookies
        except:
            pass

        driver.find_element("css selector","#APjFqb").send_keys(f'"{value} {str(year)}"' + ' ' + 'site:https://www.boxofficemojo.com/', Keys.ENTER) # We select the search box with each film and year

        try:
            driver.find_element("css selector",".LC20lb").click() # If we get results, we click on the link

            try:
                box_office = driver.find_element('css selector','.mojo-performance-summary-table > div:nth-child(4) > span:nth-child(3) > span:nth-child(1)').text # If the page shows the box office, we store the value in a variable called 'box_office'
                df_.loc[index, 'box_office'] = box_office

            except:
                df_.loc[index, 'box_office'] = np.nan # If not, we store the value as null
        except:
            df_.loc[index, 'box_office'] = np.nan

        driver.quit()
        time.sleep(2)  # Esperar 2 segundos antes de abrir el navegador nuevamente

    driver.quit()

In [ ]:

for Ã±



    scrapeo(df_sin_url)